services:
  orders-api:
    build:
      context: .
      dockerfile: src/Orders/Orders.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Database: "Host=postgres;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"
      ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672/"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "orders-api"
    ports:
      - "5176-5178:8080"
    networks:
      - outbox-network
      - observability
    restart: unless-stopped
    deploy:
      replicas: 3

  notification-consumer:
    build:
      context: .
      dockerfile: src/Notification/Notification.Consumer/Dockerfile
    container_name: outbox-notification-consumer
    environment:
      DOTNET_ENVIRONMENT: Production
      ConnectionStrings__Database: "Host=postgres;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"
      ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672/"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "notification-consumer"
    networks:
      - outbox-network
      - observability
    restart: unless-stopped

  inventory-consumer:
    build:
      context: .
      dockerfile: src/Inventory/Inventory.Consumer/Dockerfile
    container_name: outbox-inventory-consumer
    environment:
      DOTNET_ENVIRONMENT: Production
      ConnectionStrings__Database: "Host=postgres;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"
      ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672/"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "inventory-consumer"
    networks:
      - outbox-network
      - observability
    restart: unless-stopped

networks:
  outbox-network:
    external: true
    name: outbox-network
  observability:
    external: true
    name: observability-grafana-stack_observability
