{
 "title": "Outbox Processor (Dashboard)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Processed Messages (sec)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_messages_processed_total[$__range])) / $__range_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Messages (sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(outbox_messages_processed_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Messages (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_fetch_duration_milliseconds_sum[$__range]))/sum(increase(outbox_fetch_duration_milliseconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Messages (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_update_duration_milliseconds_sum[$__range]))/sum(increase(outbox_update_duration_milliseconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}